Update the-gist-of-mobx.md
mobxjs/zh.mobx.js.org pull request #1
Opened 2021-02-21 12:33 UTC by WanderWang

2021-02-21 12:58 UTC, iChenLei commented
感谢同学的参与，目前翻译流程还未完善，我尽快整理好流程写到README.md中。目前还未确定文档托管在netlify还是vercel中，正在申请vercel的免费开源项目支持（vercel访问速度比netlify快，体验好一点）。你修改后可以通过preview检查是否有格式展示的问题，我们的文档项目在每次PR提交之后自动触发netlify和vercel的构建，生成预览网址。:heart:

2021-02-21 13:05 UTC, WanderWang commented
好的，感谢

2021-02-22 02:12 UTC, WanderWang commented
@iChenLei 请问在你们调整完翻译的基础设施和流程之前，我是否可以继续完善这个 PR，把 the gist of mobx 这个页面翻译完全？

2021-02-22 02:30 UTC, iChenLei commented
@WanderWang 请继续您的工作，直接在Github提PR是我们的核心流程，您的工作可以照常进行。

我所说的是 我需要提供一个完整的翻译Guide，这对于想要参与但是不怎么会使用Github同学来说很重要。另外就是我们会提供Mobx电脑贴纸和Mobx6 CheatSheet Paper奖励，这些工作还在进行中。最后就是 zh.mobx.js.org目前还不能访问的原因是，我们正在和vercel官方交涉以确定最终将文档托管在哪个平台。因为我有正式的工作，所以这些事情不能立马完成，但我保证在本周完成所有的事项。最好，非常感谢您的积极参与，特别是在我还没有公开宣传此活动的前提下。

2021-02-28 01:57 UTC, WanderWang commented
@iChenLei  这一部分章节已经翻译完，但是也存在一些问题，我相信其他的翻译者也会遇到，我先提出一些：

1. 术语统一，比如 Model -> 业务模型
2. 部分术语是否采用英文，比如 State , Action 等

2021-02-28 12:45 UTC, iChenLei commented
> @iChenLei 这一部分章节已经翻译完，但是也存在一些问题，我相信其他的翻译者也会遇到，我先提出一些：
> 
> 1. 术语统一，比如 Model -> 业务模型
> 2. 部分术语是否采用英文，比如 State , Action 等

确实是一个问题，个人喜欢保留英文，听一下别的同学的意见 cc @BlackHole1 @wangjq4214

2021-02-28 13:21 UTC, wangjq4214 commented
这确实一个问题，我觉得像 reaction、Action 之类的确实需要保留，我并不能找到特别贴切的词汇来翻译。

再提出一个问题，我们在格式方面是否需要统一：
- 比如保留的英文单词、链接的左右两端是否添加空格
- 保留的单词大小写等

2021-03-02 01:59 UTC, wangjq4214 reviewed
有一些建议 欢迎讨论

2021-03-02 01:59 UTC, wangjq4214 commented on docs/the-gist-of-mobx.md
> +因此，上述示例中的`onClick`事件处理器调用`toggle` Action 后，会使适当的`TodoView`组件重绘，但仅当未完成任务的数量发生更改时才会使 `TodoListView` 组件重绘。
适当=>对应

2021-03-02 01:59 UTC, wangjq4214 commented on docs/the-gist-of-mobx.md
> +你不太经常会需要它们，它们可以可以使用 [`autorun`](reactions.md#autorun) ,[`reaction`](reactions.md#reaction) 或 [`when`](reactions.md#when) 方法来订制你的特殊业务场景。
你不太经常会需要它们=>通常情况下你不需要使用它们
他们可以可以使用=>可以使用

2021-03-02 01:59 UTC, wangjq4214 commented on docs/the-gist-of-mobx.md
> +_MobX对在执行跟踪函数期间读取的任何现有可观察属性作出反应_
反应=>响应
缺少句号

2021-03-02 01:59 UTC, wangjq4214 commented on docs/the-gist-of-mobx.md
> +要了解更多关于MobX如何确定需要对哪些可见物作出反应的信息，请查看 [理解反应](understanding-reactivity.md) 章节。
可见物=>可观察对象
反应=>响应

2021-03-02 01:59 UTC, wangjq4214 commented on docs/the-gist-of-mobx.md
> +Mobx 使用在 _action_ 改变 _state_ 时使用单向数据流，进而更新所有受影响的 _view_
Mobx 使用单向数据流，利用 _action_ 改变 _state_，进而更新所有受影响的 _view_。

2021-03-02 01:59 UTC, wangjq4214 commented on docs/the-gist-of-mobx.md
> +1. 所有的 _derivations_ 将在 _state_ 改变时**自动更新**。因此不可能观察中间值。
所有的 _derivations_ 将在 _state_ 改变时**自动且原子化地更新**。因此无法观察中间值。

2021-03-02 01:59 UTC, wangjq4214 commented on docs/the-gist-of-mobx.md
> +2. 所有的 _dervations_ 默认将会**同步**更新，这意味着 _action_ 可全在 _state_ 改变之后安全的直接调用 computed 值。
_action_ 可以在更改 _state_ 之后安全的直接获得 computed 值。

2021-03-02 01:59 UTC, wangjq4214 commented on docs/the-gist-of-mobx.md
> +想了解更多背景上下文，请查阅 [MobX背后的基本原则](https://hackernoon.com/the-fundamental-principles-behind-mobx-7a725f71f3e8)
删掉上下文是不是好一点

2021-03-02 01:59 UTC, wangjq4214 commented on docs/the-gist-of-mobx.md
> +如果您发现很难采用MobX的心智模型，请将其配置为非常严格，并在运行时在您偏离这些模式时发出警告。查看[linting MobX](configuration.md#linting-options)章节。
如果您发现很难适应 MobX 的心智模型，请将其配置为严格模式，在运行时偏离这些模式的情况下将会发出警告。查看 [linting MobX](configuration.md#linting-options)章节。

2021-03-02 02:50 UTC, WanderWang commented on docs/the-gist-of-mobx.md
> +`observer` 将 React 组件转化为了从数据到渲染的派生过程。
我觉得这里可能需要体现一下“派生”这个词，因为这一小节的标题是“ 创建 Derivations 以便自动对 State 变化进行响应”。但是又存在 Derivations 这个词是否要翻译的问题，确实比较纠结

2021-03-02 02:53 UTC, WanderWang commented
感谢 @wangjq4214 的校对，除了一个问题之外，其他内容我已经按照你的校对意见修改好。
关于你提出的格式（比如括号、句号、空格）等问题，我认为应该在翻译过程中内置一个脚本，通过 git 钩子的方式来保证规范，而不是要求翻译者自行遵循规范。具体的钩子逻辑我尝试采用 NodeJS 编写一个，但是钩子本身和 github 的工作流这一块我并没有做过，可能需要其他人来协助

2021-03-03 08:35 UTC, wangjq4214 commented
@WanderWang 使用 git 钩子保证的想法很好，我周末也研究一下

2021-03-12 10:07 UTC, Neo42 commented
可以用 [husky](https://github.com/typicode/husky) 来实现 git 钩子

2021-03-12 10:23 UTC, Neo42 requested changes

2021-03-12 10:23 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +sidebar_label: MobX 主旨
"gist" 翻译成“要旨”、“精要”或者“要领”会不会更好一点？

2021-03-19 02:54 UTC, wuxyman commented on docs/the-gist-of-mobx.md
> +sidebar_label: MobX 主旨
"要点" 似乎不错，主旨感觉太机械

2021-03-19 02:57 UTC, wuxyman commented
最近刚好做项目再考虑数据统一工具，就用mobx，索性就用了最新版，但是中文翻译没有最新版，就看到你们在找翻译，希望有机会参与翻译项目，周末再认真看一下工作流

2021-03-26 09:37 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +将 State 存储在任何您喜欢的数据结构中：普通对象、数组、类、循环数据结构或引用。这与MobX的工作方式无关。
```suggestion
将 State 存储在任何您喜欢的数据结构中：普通对象、数组、类、循环数据结构或引用。这对于MobX的运作方式来说并不重要。
```

2021-03-26 09:46 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +使用 `observable` 就像将对象的属性放在Excel表格的单元格中。但是和单元格不同的是，他们的值不仅仅是数值，也可以是引用、对象和数组。
```suggestion
使用 `observable` 就像将对象的属性放在Excel表格的单元格中。但是和单元格不同的是，他们的值不仅可以是数值，也可以是引用、对象和数组。
```

2021-03-26 09:49 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +接下来我们看一下被我们标记为 `action` 的`toggle`
```suggestion
但是被我们标记为 `action` 的 `toggle` 呢？
```

2021-03-26 09:55 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +_Action(动作)_ 是任意可以改变 _State(状态)_ 的代码，比如用户事件处理、后端推送数据处理、调度器事件处理等等。
```suggestion
_Action(动作)_ 是任意一段可以改变 _State(状态)_ 的代码，比如用户事件、后端数据推送、调度器事件等等。
```

2021-03-26 10:00 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +Action 就像用户在Excel单元格中输入了新的值。
```suggestion
一个 action 就像在电子表单的单元格中输入新值的用户。
```

2021-03-26 10:14 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +在 `Todo` 类中，我们可以看到 `toggle` 方法改变了 `finished` 属性的值，而 `finished` 是被标记为 `observable` 的。建议您将所有修改 `observable` 值的代码标记为 [`action`](actions.md)。MobX 可以自动进行事务处理以轻松实现最佳性能。
```suggestion
在上面的 `Todo` 类中，你可以看到我们有一个可以改变 `finished` 值的 `toggle` 方法。而 `finished` 被标记为了 `observable`。建议您将所有修改 `observable` 值的代码标记为 [`action`](actions.md)。这样 MobX 就可以自动进行事务处理，轻松实现最佳性能。
```

2021-03-26 10:28 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +使用 Action 可以帮助您更好地组织代码，并防止您在无意中修改 State。
```suggestion
使用 Action 可以帮助您更好地组织代码，并防止您在本来无意的情况下不经意间修改 State。
```

2021-03-26 10:33 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +您代码中的每一个方法只应完成上述两个目标中的一个。
```suggestion
您代码中的每一个方法最多只应该完成上述两个目标中的其中一个。
```

2021-03-26 13:14 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +### 3. 创建 Derivations 以便自动对 State 变化进行响应
```suggestion
### 3. 创建自动响应 state 变化的 derivations
```

2021-03-28 05:15 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +_任何_ 来源是_State(状态)_ 并且不需要进一步交互的东西都是 Derivation(派生)。
```suggestion
_任何_ 从 _state(状态)_ 中派生出来的、不需要进一步交互的值都是 derivation(派生)。
```

2021-03-28 05:31 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +-   _后端集成_ , 比如发送改变到服务器端
```suggestion
-   _后端集成_ , 比如把改变发送到服务器
```

2021-03-28 06:05 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +-   _Computed values_,总是可以通过纯函数从当前的可观测 State 中派生。
```suggestion
-   _Computed values_，始终可以通过一个纯函数从当前的可观测 State 中派生出来。
```

2021-03-28 06:11 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +当最开始使用MobX时，人们容易过度使用 _Reaction_。
```suggestion
一开始使用MobX时，人们容易过度使用 _Reaction_。
```

2021-03-28 06:15 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +黄金法则是，如果要基于当前 State 创建值，请始终使用 _computed_。
```suggestion
黄金准则是，如果你想要基于当前 State 创建一个值，请始终使用 _computed_。
```

2021-03-28 06:20 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +你可以通过定义 getter 方法并使用 `makeObservable` 将其标记为 `computed` 的方式创建一个 _computed_ 值。
```suggestion
想要创建一个 _computed_ 值的话，就用 JS 中的 getter 函数 `get` 定义一个属性并用 `makeObservable` 将其标记为 `computed`
```

2021-03-28 06:32 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +只要确保所有你想随时间改变的属性都被标记为`observable`，这样MobX就可以跟踪它们。
```suggestion
只要确保所有你想随时间改变的属性都被标记为`observable` 就好，这样MobX就可以跟踪它们。
```

2021-03-28 06:39 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +Mobx 会确保 `unfinishedTodoCount` 会在todos数组发生变化中或者 todos中的一个对象中的 `finished`属性被修改时自动更新。
```suggestion
Mobx 会确保 `unfinishedTodoCount` 在一个待办事项被添加进来或者多个 `finished` 属性中的其中一个被修改时自动更新。
```

2021-03-28 06:46 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +这些计算类似于 Excel 单元格中的公式。它们仅在需要时自动更新。也就是说，如果有观察者使用其结果时才会更新。也就是说，如果有有人关心其结果时才会更新。
```suggestion
这些计算类似于微软 Excel 等电子表格程序中的公式。它们会自动更新，但只有在必要时——也就是说，当某些值对它们的输出结果感兴趣时——才会更新。
```

2021-03-28 06:46 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +#### 3.2. 使用 reaction 对副作用建模
```suggestion
#### 3.2. 使用 reaction 对副作用进行建模
```

2021-03-28 06:53 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +作为用户，要想在屏幕上看到状态或计算值的变化，就需要一个重新绘制部分GUI的 _reactions_ 。
```suggestion
对你来说，作为用户，要想在屏幕上看到状态或计算值的变化，就需要一个重绘部分 GUI 的 _reaction_ 。
```

2021-03-28 07:06 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +Reaction 和 computed 类似，但并不产生信息，而是产生副作用，如打印到控制台、发出网络请求、增量更新 React 组件树以便更新DOM等。
```suggestion
Reactions 和计算值类似，但它们并不产出数据，而是产出副作用，比如打印到控制台、发送网络请求、逐步更新 React 组件树来修补 DOM 等。
```

2021-03-28 07:07 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +-   _Reactions_, 当 State 改变时需要自动运行的副作用 (命令式编程和响应式编程之间的桥梁)
```suggestion
-   _Reactions_, 当 State 改变时需要自动运行的副作用 (指令式编程和响应式编程之间的桥梁)
```

2021-03-28 07:12 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +注意，action 和 reaction 都可能引起副作用。
```suggestion
注意，用 action 和 reaction 都可以触发副作用。
```

2021-03-28 07:20 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +副作用应有一个清晰的、显式的起源，例如在提交表单时发出网络请求，应该从相关的事件处理程序显式触发。
```suggestion
像是在提交表单时发出网络请求这样的有清晰明确的触发原由的副作用，应该从相关的事件处理程序中显式触发。
```

2021-03-28 07:30 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +如果使用 React，你可以将组件用[安装](installation.md#installation)中下载的包中的[`observer`](react-integration.md)函数来包装起来，以便让组件成为响应式的。在这个示例中，我们将用更轻量的 `mobx-react-lite` 包。
```suggestion
如果你用的是 React，那么你就可以使用你在安装时所选的绑定包中的 `observer` 函数把组件包装起来，从而把它们变成响应式组件。
```

2021-03-28 07:40 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +`observer` 将 React 组件转化为了从数据到渲染的派生过程。
```suggestion
`observer` 会把 React 组件转化成它们所渲染的数据的 derivations。
```

2021-03-28 07:49 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +当使用 MobX 的时，不存在“智能组件”和“哑巴组件”。所有的组件在渲染时都是智能的，但是在定义时是按照哑巴组件的方式去定义的。MobX会简单确定这个组件是否需要进行重绘，并止步于此。
```suggestion
在使用 MobX 时，不存在智能组件或者傻瓜组件。所有的组件都是智能渲染的，但却是以一种傻瓜式的方式被定义出来的。简单地说，MobX 会确保组件始终在需要时被重新渲染，除此之外都不会被重新渲染。
```

2021-03-28 08:01 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +因此，上述示例中的`onClick`事件处理器调用`toggle` Action 后，会使对应的`TodoView`组件重绘，但仅当未完成任务的数量发生更改时才会使 `TodoListView` 组件重绘。
```suggestion
因此，在上述示例中，随着 `onClick`事件处理程序对 `toggle` action进行调用，它会迫使相应的 `TodoView` 组件重新渲染，但只有在未完成任务的数量发生更改时，它才会使 `TodoListView` 组件重新渲染。
```

2021-03-28 08:44 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +如果移除了`Tasks left`这行代码（或者把他拆分到另一个组件中）,`TodoListView`组件就不再 `toggle` 执行时产生重绘了。
```suggestion
如果你移除 `Tasks left` 这行代码（或者把它放到另外一个组件中），`TodoListView` 组件就不会在你划掉一个待办任务时重新渲染了。
```

2021-03-28 08:46 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +您可以查阅[与 React 集成](react-integration.md)来了解更多有关 React 是如何与 MobX 协同运作的。
```suggestion
想了解更多有关 React 如何与 MobX 协同运作的内容，您可以查阅[与 React 集成](react-integration.md)部分。
```

2021-03-28 08:55 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +让我们仔细看看下面的这些概念，或者在[10分钟的MobX和React简介](https://mobx.js.org/getting-started)中，您可以通过交互方式逐步深入了解这些概念，并构建一个简单的待办事项列表(Todo List)应用程序。
```suggestion
让我们仔细看看下面的这些概念，或者在[10分钟的MobX和React简介](https://mobx.js.org/getting-started)中，你可以通过交互方式逐步深入了解这些概念，并构建一个简单的待办事项列表(Todo List)应用程序。
```

2021-03-28 09:41 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +您可以查阅[与 React 集成](react-integration.md)来了解更多有关 React 是如何与 MobX 协同运作的。
```suggestion
您可以查阅[与 React 集成](react-integration.md)来了解更多有关 React 是如何与 MobX 协同运作的内容。
```

2021-03-28 09:49 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +通常情况下你不需要使用它们，可以使用 [`autorun`](reactions.md#autorun) ,[`reaction`](reactions.md#reaction) 或 [`when`](reactions.md#when) 方法来订制你的特殊业务场景。
```suggestion
你很少会需要它们，不过它们可以由你根据具体情况使用 [`autorun`](reactions.md#autorun)、[`reaction`](reactions.md#reaction) 或 [`when`](reactions.md#when) 方法创建出来。
```

2021-03-28 10:08 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +为什么每次 `unfinishedTodoCount`发生改变时都会输出日志信息呢？答案是以下法则：
```suggestion
为什么每次 `unfinishedTodoCount`发生改变时都会输出日志信息呢？答案是这个经验法则：
```

2021-03-28 10:13 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +_MobX对在执行跟踪函数期间读取的任何现有可观察属性作出响应_。
```suggestion
_Mobx 会在一个被追踪的函数执行期间对所有被读取的可观察属性作出反应_。
```

2021-03-28 10:17 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +要了解更多关于MobX如何确定需要对哪些可观察对象作出响应的信息，请查看 [理解反应](understanding-reactivity.md) 章节。
```suggestion
要了解更多关于MobX如何确定需要对哪些可观察对象作出响应的信息，请查看 [理解响应性](understanding-reactivity.md) 章节。
```

2021-03-28 10:29 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +如果您发现很难适应 MobX 的心智模型，请将其配置为严格模式，在运行时偏离这些模式的情况下将会发出警告。更多信息请查看[linting MobX](configuration.md#linting-options)章节。
```suggestion
如果你觉得很难适应 MobX 的心智模型，那么可以把它配置得很严格，这样一旦你背离了这些模式，它就会在运行时向你发出警告。更多信息请查看[linting MobX](configuration.md#linting-options)章节。
```

2021-03-28 10:39 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +Mobx 使用单向数据流，利用 _action_ 改变 _state_ ，进而更新所有受影响的 _view_
```suggestion
Mobx 使用的是一个单向数据流，其中 _action_ 会改变 _state_ ，而这会进而更新所有受影响的*视图*。
```

2021-03-28 10:53 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +1. 所有的 _derivations_ 将在 _state_ 改变时**自动且原子化地更新**。因此不可能观察中间值。
```suggestion
1. 所有的 _derivations_ 将在 _state_ 改变时**自动且原子化地更新**。因此永远不可能观察到中间值。
```

2021-03-28 11:02 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +2. 所有的 _dervations_ 默认将会**同步**更新，这意味着 _action_ 可以在 _state_ 改变 之后安全的直接获得 computed 值。
```suggestion
2. 所有 _dervations_ 都会默认**同步**更新，这意味着——比方说—— _action_ 在其更改 _state_ 之后马上就可以安全、直接地查到 computed 值。
```

2021-03-28 11:07 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +想了解更多背景，请查阅 [MobX背后的基本原则](https://hackernoon.com/the-fundamental-principles-behind-mobx-7a725f71f3e8)
```suggestion
想了解更多背景内容，请查阅[MobX背后的基本原则](https://hackernoon.com/the-fundamental-principles-behind-mobx-7a725f71f3e8)。
```

2021-03-28 11:18 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +3. _computed value_ 的更新是**惰性**的，任何 computed value 在需要他们的副作用发生之前都是不激活的。
```suggestion
3. _computed value_ 的更新是**惰性**的，所有不在使用中的 computed value 都只有当有副作用需要它们时才会被更新。
```

2021-03-28 11:23 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +4. 所有的 _computed value_ 都应是**纯函数**,他们不应该修改 _state_。
```suggestion
4. 所有的 _computed value_ 都应是**纯函数**，它们不应该修改 _state_。
```

2021-03-28 11:30 UTC, Neo42 commented on docs/the-gist-of-mobx.md
> +## 提示
```suggestion
## 代码检查
```

2021-04-06 03:12 UTC, WanderWang commented
@Neo42 前段时间一直在忙，感谢你的校对，这一部分内容我会在今晚完善。

2021-04-06 14:07 UTC, Neo42 commented
@WanderWang 实在抱歉，你的这篇是我校对的第一篇，当时还没掌握方法，多有冒犯，请见谅😅。建议改动的都已经写明理由，风格方面的建议仅供参考~

2021-08-21 09:10 UTC, merged