docs: translate observable-state.md
mobxjs/zh.mobx.js.org pull request #10
Opened 2021-02-27 09:07 UTC by wangjq4214

已完成翻译 observable-state.md

2021-02-27 09:12 UTC, iChenLei commented
cc @WanderWang @BlackHole1 校对一下？
另外 #7 和 #10 重复 #5 和 #8 重复，我整理下issue和READEME,不然重复的事情还会发生。

2021-02-27 10:44 UTC, BlackHole1 requested changes

2021-02-27 10:44 UTC, BlackHole1 commented on docs/observable-state.md
> +**所有的不可观察**（stateless）的字段（`action`, `flow`）都是 **不可写的**。
stateless => 无状态

2021-02-27 10:44 UTC, BlackHole1 commented on docs/observable-state.md
> +与第一个使用 `makeObservable` 的示例相反，`observable` 支持向对象添加（删除）字段。
与第一个例子中的 `makeObservable` 不同，`observable` 支持向对象添加（和删除）_字段_。

2021-02-27 10:44 UTC, BlackHole1 commented on docs/observable-state.md
> +这对于动态对象，数组，Maps 和 Sets 之类的集合而言，极大的提升了它们的 `可观察性`。
这使得 `observable` 非常适合用于动态对象、Array、Maps、Sets 之类的集合。

2021-02-27 10:44 UTC, BlackHole1 commented on docs/observable-state.md
> +因为不需要显式地提及新成员，所以使用 `makeAutoObservable` 函数比使用 `makeObservable` 函数，会写更少的代码，且更容易维护。
与使用 `makeObservable` 相比，`makeAutoObservable` 函数更紧凑，也更容易维护，因为新成员不需要显式地提及。

2021-02-27 10:44 UTC, BlackHole1 commented on docs/observable-state.md
> +可以使用类似的方法与 Map 和 Set 等集合一同工作。
处理 Map 和 Set 集合的工作原理类似。

2021-02-27 10:44 UTC, BlackHole1 commented on docs/observable-state.md
> +第二个区别是，`observable` 创建一个 [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) 对象， 以便在将该对象用作动态查找图时能够捕获将要添加的属性。
"对象， 以便在将该"，逗号之后存在多余空格

2021-02-27 10:44 UTC, BlackHole1 commented on docs/observable-state.md
> +如果将要转化为可观察的对象有既定的结构，换句话说其中的所有成员都是预先知道的，我们推荐使用 `makeObservable`，因为非代理对象具有更快的速度，并且更容易在 debugger 中进行追踪检查，并且可以使用 `console.log` 方便地进行打印。
如果你想让可观察的对象具有一个常规的结构，其中所有的成员都是事先已知的，我们建议使用 `makeObservable`，因为非代理对象速度更快，而且它们更容易在 `debugger` 和 `console.log` 中检查。

2021-02-27 10:44 UTC, BlackHole1 commented on docs/observable-state.md
> +## 将可观察变量转化回原始 JavaScript 集合
将 observable 转换回普通的 JavaScript 集合

2021-02-27 10:44 UTC, BlackHole1 commented on docs/observable-state.md
> +你不能在 [subclass](subclassing.md) 子类中传递不同的 options。
你不能在 [子类](subclassing.md) 中传递不同的 options。

2021-02-27 10:44 UTC, BlackHole1 commented on docs/observable-state.md
> +但是，繁重的继承很容易成为 foot-guns，因此如果使用类，请尽量使其保持简单。
但是，繁重的继承很容易成为军火库

2021-02-27 10:44 UTC, BlackHole1 commented on docs/observable-state.md
> +因此，即使您并不喜欢使用类，我们也鼓励您尽可能多的使用类的写法。如果其他写法更适合你，也可以使用其他写法。
因此，尽管稍微倾向于使用类，但如果有更适合您的，我们肯定会鼓励您偏离这种风格。

2021-02-27 11:24 UTC, BlackHole1 commented
@iChenLei 我这边已经没有问题了

2021-03-02 03:00 UTC, WanderWang commented on docs/observable-state.md
> +使用：
使用方式：

2021-03-02 03:01 UTC, WanderWang commented on docs/observable-state.md
> +使用：
使用方式：

2021-03-30 14:18 UTC, Neo42 commented on docs/observable-state.md
> +使用：
```suggestion
用法：
```

2021-03-30 14:23 UTC, Neo42 commented on docs/observable-state.md
> +-   `observable` 定义一个存储在 state 中的可追踪字段。
```suggestion
-   `observable` 定义一个用来存储 state 的可追踪字段。
```
"field that stores the state” 表示 field 把 state 存储起来，或者 state 存储在 field 中

2021-03-30 14:56 UTC, Neo42 commented on docs/observable-state.md
> +使得对象可观察的关键是使用 `makeObservable` 为每个属性指定特殊的注解。
```suggestion
使得对象可观察的基本方法是使用 `makeObservable` 为每个属性指定一个特殊的注解。
```
“basics” 意为“基本、基础”，“关键”的英文应该是 “key”

2021-03-30 14:59 UTC, Neo42 commented on docs/observable-state.md
> +-   `action` 将一个可以修改 state 的方法标记为 action。
```suggestion
-   `action` 将一个方法标记为可以修改 state 的 action。
```
“that will modify the state” 修饰的是 “action”，而不是 “method”

2021-03-30 15:00 UTC, Neo42 commented on docs/observable-state.md
> +-   `computed` 标记一个可以由 state 派生处新的值并且缓存输出的 getter。
```suggestion
-   `computed` 标记一个可以由 state 派生处新的值并且缓存其输出的 getter。
```
“its” 最好翻译出来

2021-03-30 15:29 UTC, Neo42 commented on docs/observable-state.md
> +使用：
```suggestion
用法：
```

2021-03-31 02:31 UTC, Neo42 commented on docs/observable-state.md
> +但是，繁重的继承很容易成为军火库，因此如果使用类，请尽量使其保持简单。
```suggestion
但是，繁重的继承模式很容易给您自己带来不必要的麻烦，因此如果您想使用类，请尽量使其保持简单。
```
"foot-guns" 这个词来自 “shoot oneself in the foot”（直译“开枪打到自己的脚”，对应中文的“搬起石头砸自己的脚”），不过如果直接翻译出来的话可能会有些不礼貌，建议换一种不带感情色彩的说法。

2021-03-31 04:10 UTC, Neo42 commented on docs/observable-state.md
> +像数组，Maps 和 Sets 这样的集合都可以被自动地转化为可观察对象。
```suggestion
像数组，Maps 和 Sets 这样的集合都将被自动转化为可观察对象。
```

2021-03-31 04:19 UTC, Neo42 commented on docs/observable-state.md
> +`observable` 注解可以作为一个函数进行调用，从而将整个对象立刻变成可观察的。
```suggestion
`observable` 注解可以作为一个函数进行调用，从而将整个对象一次性变成可观察的。
```
“at once” 除了可以指“立刻”还可以指“一次性；同时”："Computers that can do many things at once." 这里用后者比较合适

2021-03-31 04:28 UTC, Neo42 commented on docs/observable-state.md
> +这个函数可以捕获_已经存在_的对象属性并且使得他们可观察。任何 JavaScript 对象（包括类的实例）都可以作为 `target` 被传递给这个函数。
```suggestion
这个函数可以捕获_已经存在_的对象属性并且使得它们可观察。任何 JavaScript 对象（包括类的实例）都可以作为 `target` 被传递给这个函数。
```
*“它们”

2021-03-31 04:33 UTC, Neo42 commented on docs/observable-state.md
> +一般情况下，在类的构建函数中调用 `makeObservable` 函数，并且将 `this` 作为其第一个参数。
```suggestion
一般情况下，`makeObservable` 要在类的构造函数中调用，并且它的第一个参数是 `this` 。
```
*“构造函数”是比较通用的说法；后半句缺少主语，读起来不太通顺，建议变一下句式。

2021-03-31 05:03 UTC, Neo42 commented on docs/observable-state.md
> +派生额外信息和接受参数的方法（例如：`findUsersOlderThan(age: number): User[]`）不需要任何注解。
```suggestion
派生数据和接受参数的方法（例如：`findUsersOlderThan(age: number): User[]`）不需要任何注解。
```
建议把 “information” 译为“数据”比较符合语境（[见MW的解释3](https://www.merriam-webster.com/dictionary/information)）

2021-03-31 05:17 UTC, Neo42 commented on docs/observable-state.md
> +它们的读取操作被其他副作用调用时仍然会被跟踪，但是它们输出出于避免内存泄漏的目的将不会被记录。更详细的信息可以查看 [MobX-utils computedFn {🚀}](https://github.com/mobxjs/mobx-utils#computedfn)。
```suggestion
当从一个 reaction 中调用它们时，它们的读取操作仍然会被跟踪，但是为了避免内存泄漏，它们的输出将不会被记忆化。更详细的信息可以查看 [MobX-utils computedFn {🚀}](https://github.com/mobxjs/mobx-utils#computedfn)。
```
把状语单拎出来翻译会比较容易理解，也不容易翻错。

2021-03-31 05:28 UTC, BlackHole1 commented on docs/observable-state.md
> +但是，繁重的继承很容易成为军火库，因此如果使用类，请尽量使其保持简单。
这个真的学习到了

2021-03-31 08:26 UTC, Neo42 commented on docs/observable-state.md
> +通过 `override` 注解 [支持的子类有一些限制](subclassing.md)。
```suggestion
Mobx 通过 `override` 注解 [支持子类的使用，但有一些限制](subclassing.md)。
```

2021-03-31 08:50 UTC, Neo42 commented on docs/observable-state.md
> +示例中的差异仅说明如何将 MobX 应用于不同的编程风格。
```suggestion
示例中的差异就展示了将 MobX 应用于不同编程风格的方法。
```

2021-03-31 08:57 UTC, Neo42 commented on docs/observable-state.md
> +与第一个例子中的 `makeObservable` 不同，`observable` 支持向对象添加（和删除）字段。
```suggestion
与第一个例子中的 `makeObservable` 不同，`observable` 支持为对象添加（和删除）字段。
```
“向对象删除”有点不通顺

2021-03-31 09:30 UTC, Neo42 commented on docs/observable-state.md
> +这使得 `observable` 非常适合用于动态对象、Array、Maps、Sets 之类的集合。
```suggestion
这使得 `observable` 非常适合用于像动态键控的对象、数组、Maps 和 Sets 之类的集合。
```
C# 里有 `KeyedCollection`（键控集合）可以拿来用

2021-03-31 09:36 UTC, Neo42 commented on docs/observable-state.md
> +`makeAutoObservable` 类似于 `makeObservable`，在默认情况下它将推断所有的属性。你仍然可以使用 `overrides` 重写某些注解的默认行为。
```suggestion
`makeAutoObservable` 就像是加强版的 `makeObservable`，在默认情况下它将推断所有的属性。你仍然可以使用 `overrides` 重写某些注解的默认行为。
```
“on steroids”原意是“吃了类固醇（兴奋剂）的”，习惯引申为“加强版”

2021-03-31 09:57 UTC, Neo42 commented on docs/observable-state.md
> +查看上面的代码获取示例。
```suggestion
查看上面的代码分页获取示例。
```

2021-03-31 10:14 UTC, Neo42 commented on docs/observable-state.md
> +与使用 `makeObservable` 相比，`makeAutoObservable` 函数更紧凑，也更容易维护，因为新成员不需要显式地提及。
```suggestion
与使用 `makeObservable` 相比，`makeAutoObservable` 函数更加紧凑也更容易维护，因为不需要显式地写出要转化的值。
```
建议这里采用意译，直译的话实在不太符合中文语言习惯。

2021-03-31 10:16 UTC, Neo42 commented on docs/observable-state.md
> +然而，`makeAutoObservable` 不能被用于具有 super 的 [子类](subclassing.md)。
```suggestion
然而，`makeAutoObservable` 不能被用于具有 super 的类或 [子类](subclassing.md)。
```
类或子类是相互独立的

2021-03-31 13:02 UTC, Neo42 commented on docs/observable-state.md
> +-   任何（包含继承的）是 `function` 的成员都将使用 `autoAction` 注解标记。
```suggestion
-   任何包含一个 `function` 值的（包括继承的）成员都将使用 `autoAction` 注解标记。
```
“任何包含继承的”读起来可能会有歧义，建议放在后面

2021-03-31 13:33 UTC, Neo42 commented on docs/observable-state.md
> +-   任何（包含继承的）的 generator 函数都将使用 `flow` 注解标记。（需要注意，在某些编译器配置中无法检测到 generator 函数，如果 flow 不能正常运行，请明确的指定 `flow` 注解。）
```suggestion
-   任何是 generator 函数的成员（包括继承来的）都将使用 `flow` 注解标记。（需要注意，generator 函数在某些编译器配置中无法被检测到，如果 flow 没有正常运行，请务必明确地指定 `flow` 注解。）
```
“在……中无法检测到……”不太通顺，直接按原文被动关系翻译就可以，如果变为主动句式的话会缺少主语

2021-03-31 14:10 UTC, Neo42 commented on docs/observable-state.md
> +同样的，`overrides` 对象可以为特定的对象提供特定的注解。
```suggestion
同样，你可以传入一个 `overrides` 对象来为特定的成员提供特定的注解。
```

2021-03-31 15:23 UTC, Neo42 commented on docs/observable-state.md
> +处理 Map 和 Set 集合的工作原理类似。
```suggestion
使用 Map 和 Set 集合时，用法和这里类似。
```
“work with” 多数情况下指[“使用”](https://idioms.thefreedictionary.com/work+with)
这里主要是通过例子展示用法，所以把 “work similarly” 翻译成“用法类似”可能更合适。

2021-03-31 15:46 UTC, Neo42 commented on docs/observable-state.md
> +可观察的数组还有一些额外的使用函数：
```suggestion
可观察的数组还有一些特别好用的实用函数：
```
[nifty](https://dictionary.cambridge.org/dictionary/english/nifty)
“还”和“额外”重复了

2021-03-31 15:49 UTC, Neo42 commented on docs/observable-state.md
> +MobX 无法使原始值可观察，因为他们在 JavaScript 中是不可变的（但是可以将他们 [包装](api.md#observablebox)）。
```suggestion
MobX 无法使原始值可观察，因为它们在 JavaScript 中是不可变的（但是 Mobx 可以将它们 [包装](api.md#observablebox)起来）。
```
*它们

2021-03-31 15:51 UTC, Neo42 commented on docs/observable-state.md
> +-   `replace(newItems)` 将数组中现有的成员全部替换成 newItems。
```suggestion
-   `replace(newItems)` 将数组中现有的元素全部替换成 newItems。
```
*元素

2021-03-31 16:14 UTC, Neo42 commented on docs/observable-state.md
> +尽管在通常情况下不会在 MobX 的外部使用这样的机制。
```suggestion
尽管通常情况下我们不会在类库之外使用这样的机制。
```
“outside **libraries**”是复数，说明所指不是 Mobx，保险起见建议按原文“类库”翻译

2021-04-01 07:18 UTC, Neo42 commented on docs/observable-state.md
> +即使将类的实例传递给 `observable` 或者将其分配给一个 `observable` 属性，类的实例也永远不会成为可观察对象。
```suggestion
我们永远无法通过把类的实例传入 `observable` 或用其给一个 `observable` 属性赋值来将其自动转化成可观察对象。
```
pass (in)to function 后面接函数时一般译为传入
assign 赋值
*自动

2021-04-01 07:29 UTC, Neo42 commented on docs/observable-state.md
> +在类的构造函数中使得类成员成为可观察对象。
```suggestion
一般认为应由类构造函数负责将类成员转化成可观察对象。
```

2021-04-01 07:43 UTC, Neo42 commented on docs/observable-state.md
> +<details id="avoid-proxies"><summary>{🚀} **提示：** observable（proxied）与 makeObservable（unproxied）<a href="#avoid-proxies" class="tip-anchor"></a></summary>
```suggestion
<details id="avoid-proxies"><summary>{🚀} **提示：** observable（使用代理）与 makeObservable（不使用代理）<a href="#avoid-proxies" class="tip-anchor"></a></summary>
```

2021-04-01 07:54 UTC, Neo42 commented on docs/observable-state.md
> +`make(Auto)Observable` 和 `observable` 之间最主要的区别在于，`make(Auto)Observable` 修改你在第一个参数位传递的对象，而 `observable` 创建一个可观察的 _clone_ 对象。
```suggestion
`make(Auto)Observable` 和 `observable` 之间最主要的区别在于，`make(Auto)Observable` 会修改你作为第一个参数传入的对象，而 `observable` 会创建一个可观察的 _副本_ 对象。
```
*会修改、会创建
clone 副本

2021-04-01 08:10 UTC, Neo42 commented on docs/observable-state.md
> +第二个区别是，`observable` 创建一个 [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) 对象，以便在将该对象用作动态查找图时能够捕获将要添加的属性。
```suggestion
第二个区别是，`observable` 会创建一个 [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) 对象，以便能够在你将该对象当作动态查询映射使用时捕获将要添加的属性。
```
lookup map 查询映射

2021-04-01 08:21 UTC, Neo42 commented on docs/observable-state.md
> +如果你想让可观察的对象具有一个常规的结构，其中所有的成员都是事先已知的，我们建议使用 `makeObservable`，因为非代理对象速度更快，而且它们更容易在 `debugger` 和 `console.log` 中检查。
```suggestion
如果你想把一个对象转化为可观察对象，而这个对象具有一个常规结构，其中所有的成员都是事先已知的，那么我们建议使用 `makeObservable`，因为非代理对象的速度稍快一些，而且它们在调试器和 `console.log` 中更容易检查。
```
把句子主干拆出来就是 “If the object...has a regular structure..., we recommend...”
“you want to make observable” 是修饰 “object” 的，而不是句子主干

2021-04-01 08:26 UTC, Neo42 commented on docs/observable-state.md
> +因此，`make(Auto)Observable` 推荐在工厂函数中使用。
```suggestion
因此，`make(Auto)Observable` 推荐在工厂函数中使用的 API。
```

2021-04-01 09:02 UTC, Neo42 commented on docs/observable-state.md
> +值得一提的是，可以将 `{ proxy: false }` 作为 option 传递给 `observable` 获取非代理的克隆。
```suggestion
值得一提的是，可以将 `{ proxy: false }` 作为 option 传入 `observable` 获取非代理副本。
```

2021-04-01 10:05 UTC, Neo42 commented on docs/observable-state.md
> +| `observable`<br/>`observable.deep` | 定义一个存储 state 的可跟踪字段。如果可能，任何被声明为 `observable` 的字段都将是递归可观察的。也就是说，当且仅当值是纯对象，数组，Map 和 Set 时是递归可观察的。 |
```suggestion
| `observable`<br/>`observable.deep` | 定义一个存储 state 的可跟踪字段。任何被赋值给 `observable` 字段的值在可以被转化时（也就是说，当且仅当该值是纯对象，数组，Map 或 Set 时）都将被递归转化为可观察值。 |
```
被转化的是值而不是字段。

2021-04-01 10:18 UTC, Neo42 commented on docs/observable-state.md
> +| `observable.ref`                   | 类似于 `observable`，但是仅会跟踪重新分配空间的变化。分配的值本身将不会自动变为可观察的。例如，你打算将不可变数据存储在可观察字段中，请使用这个注解。 |
```suggestion
| `observable.ref`                   | 类似于 `observable`，但只有重新赋值才会被追踪。所赋的值本身并不会被自动转化为可观察值。比方说，你可以在打算将不可变数据存储在可观察字段中时使用这个注解。 |
```

2021-04-01 10:28 UTC, Neo42 commented on docs/observable-state.md
> +| `observable.shallow`               | 类似于 `observable.ref` 但是是针对集合的。任何集合的声明都会是可观察的，但是他们内容的并不会成为可观察的。 |
```suggestion
| `observable.shallow`               | 类似于 `observable.ref` 但是是用于集合的。任何所赋的集合都会被转化为可观察值，但是其内部的值并不会变为可观察值。 |
```
如果是 “declaration” 那可以翻译成“声明”，assign（ment）应该是“赋值”

2021-04-01 10:34 UTC, Neo42 commented on docs/observable-state.md
> +| `observable.struct`                | 类似于 `observable`，除了结构上与当前值相同的值，其他的值都将被忽略。 |
```suggestion
| `observable.struct`                | 类似于 `observable`，但是会忽略所赋的值中所有在结构上与当前值相同的值。 |
```
“except that” 后面是一个完整的句子，不能断开翻译

2021-04-01 12:14 UTC, Neo42 commented on docs/observable-state.md
> +| `action`                           | 使得函数成为可以修改 state 的 action。查看 [actions](actions.md) 获取更多信息。不可写。 |
```suggestion
| `action`                           | 把一个函数标记为会修改 state 的 action。查看 [actions](actions.md) 获取更多信息。不可写。 |
```

2021-04-01 12:25 UTC, Neo42 commented on docs/observable-state.md
> +| `computed`                         | 可以作为 [getter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) 使用，将其声明为可缓存的派生值。查看 [computeds](computeds.md) 获取更多信息。 |
```suggestion
| `computed`                         | 可以用在 [getter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) 上，用来将其声明为可缓存的派生值。查看 [computeds](computeds.md) 获取更多信息。 |
```
used on 用在……上，用于
如果是 used as 可以翻译成“作为……使用”

2021-04-01 13:56 UTC, Neo42 commented on docs/observable-state.md
> +| `computed.struct`                  | 类似于 `computed`，除了计算之后结果在结构上相当于之前的结果，否则不会通知观察者。 |
```suggestion
| `computed.struct`                  | 类似于 `computed`，但如果结果在重新计算后在结构上与之前的结果相等，那么观察者将不会收到通知。 |
```
“except that”后面是完整的句子

2021-04-01 14:01 UTC, Neo42 commented on docs/observable-state.md
> +| `false`                            | 不使用注解注释此属性。                                       |
```suggestion
| `false`                            | 不对此属性使用注解。                                       |
```
“注释”和“注解”最好区分开

2021-04-01 14:12 UTC, Neo42 commented on docs/observable-state.md
> +| `flow`                             | 创建一个 `flow` 管理一部进程。查看 [flow](actions.md#using-flow-instead-of-async--await-) 获取更多信息。需要注意的是，在 TypeScript 中的返回类型推断可能无效。 不可写。 |
```suggestion
| `flow`                             | 创建一个 `flow` 管理异步进程。查看 [flow](actions.md#using-flow-instead-of-async--await-) 获取更多信息。需要注意的是，推断出来的 TypeScript 返回类型可能会出错。 不可写。 |
```
*异步
[be off：出错，有瑕疵](https://idioms.thefreedictionary.com/be+off)

2021-04-01 14:44 UTC, Neo42 commented on docs/observable-state.md
> +| `autoAction`                       | 不应显式使用，而应由 `makeAutoObservable` 自动调用，以根据调用上下文将方法标识为 action 或者派生值。 |
```suggestion
| `autoAction`                       | 不应被显式调用，但 `makeAutoObservable` 内部会对其进行调用，以便根据调用上下文将方法标识为 action 或者派生值。 |
```
“but is used by” 表示陈述事实，而不是应该，如果是 “but (should be) used by” 就可以翻译为 “而应……”
“under the hood” 直译“引擎盖下”，引申为“内部”

2021-04-01 14:45 UTC, Neo42 commented on docs/observable-state.md
> +## 限制
```suggestion
## 局限性
```

2021-04-01 15:12 UTC, Neo42 commented on docs/observable-state.md
> +1. `make(Auto)Observable` 仅支持已经定义的属性。确保你的 [**编译器选项**是正确的](installation.md#use-spec-compliant-transpilation-for-class-properties)，或者在使用 `make(Auto)Observable` 之前确保已经为所有属性分配了值。如果没有正确的配置，已经声明但是没有初始化的值（例
```suggestion
1. `make(Auto)Observable` 仅支持已经定义的属性。请确保你的 [**编译器选项**是正确的](installation.md#use-spec-compliant-transpilation-for-class-properties)，或者，作为权宜之计，确保在你使用 `make(Auto)Observable` 之前已经为所有属性赋了值。如果没有正确的配置，已经声明但是没有初始化的字段（例如：`class X { y; }`）将不能被正确侦测到。
```
workaround：权宜之计
*正确

2021-04-01 15:40 UTC, Neo42 commented on docs/observable-state.md
> +1. `makeObservable` 只能注解类定义本身声明的属性。如果在子类或者超类中引入了可观察字段，则必需为那些属性本身调用 `makeObservable`。
```suggestion
1. `makeObservable` 只能注解由属性本身所在的类定义声明出来的属性。如果一个子类或超类引入了可观察字段，那么那个子类或超类必须自己为那些属性调用 `makeObservable`。
```

2021-04-07 03:09 UTC, Neo42 commented on docs/observable-state.md
> +1. `options` 参数只能提供一次。传递的 `options` 是 _“sticky”_ 的，以后不能被更改（例如，在 [子类](subclassing.md) 中）。
```suggestion
1. `options` 参数只能提供一次。被传入的 `options` 是 _“有粘性”_ 的，之后无法更改（例如，在 [子类](subclassing.md) 中）。
```
函数情境下用“传入”更好一些
sticky 最好翻译一下

2021-04-07 03:10 UTC, Neo42 commented on docs/observable-state.md
> +1. **每个字段只能被注解一次**（`override` 除外）。字段注解和配置不能在 [子类](subclassing.md) 中改变。
```suggestion
1. **每个字段只能被注解一次**（`override` 除外）。字段注解和配置在 [子类](subclassing.md) 中无法更改。
```

2021-04-07 03:16 UTC, Neo42 commented on docs/observable-state.md
> +1. 非纯对象（**classes**）的 **所有注解** 字段都是 **不可配置的**。<br>
```suggestion
1. 非普通对象（**类**）的 **所有被注解过的** 字段都是 **不可配置的**。<br>
```

2021-04-07 03:34 UTC, Neo42 commented on docs/observable-state.md
> +1. **所有不可观察**（stateless）字段（`action`，`flow`）都是 **不可写的**。<br>
```suggestion
1. **所有不可观察**（无状态）字段（`action`，`flow`）都是 **不可写的**。<br>
```

2021-04-07 03:37 UTC, Neo42 commented on docs/observable-state.md
> +1. [只有定义在**原型**上的 **`action`，`computed`，`flow`，`action.bound`** 可以在子类中被 **overriden**](subclassing.md)。
```suggestion
1. [只有定义在**原型**上的 **`action`，`computed`，`flow`，`action.bound`** 才能被子类**覆盖**](subclassing.md)。
```

2021-04-07 03:52 UTC, Neo42 commented on docs/observable-state.md
> +1. 默认情况下 _TypeScript_ 不允许注解 **private** 字段。可以通过将相关私有字段显式传递为参数来解决，例如： `makeObservable<MyStore, "privateField" | "privateField2">(this, { privateField: observable, privateField2: observable })`。
```suggestion
1. 默认情况下 _TypeScript_ 不会允许你注解**私有**字段。这个问题可以通过将相关私有字段作为泛型参数显式传入来解决，就像这样： `makeObservable<MyStore, "privateField" | "privateField2">(this, { privateField: observable, privateField2: observable })`。
```

2021-04-07 04:00 UTC, Neo42 commented on docs/observable-state.md
> +1. **优先调用 `make(Auto)Observable`** 并提供注解，这样可以缓存推测结果。
```suggestion
1. **make(Auto)Observable**的调用和注解的提供必须无条件地进行，因为这样才能使推断结果得以缓存。
```

2021-04-07 04:21 UTC, Neo42 commented on docs/observable-state.md
> +1. _EcmaScript_ 的 **private** 字段（**`#field`**）**不受支持**。当使用 _TypeScript_ 时，推荐使用 `private` 修饰符。
```suggestion
1. **不支持** _EcmaScript_ 中的**私有**字段（**`#field`**）。在你使用 _TypeScript_ 时，推荐使用 `private` 修饰符。
```

2021-04-07 04:24 UTC, Neo42 commented on docs/observable-state.md
> +1. **不支持** 在单个继承链中 **混合使用注解和装饰器** - 例如，在超类中使用了装饰器，不能再子类中使用注解。
```suggestion
1. **不支持** 在单个继承链中 **混合使用注解和装饰器** - 例如，在超类中使用了装饰器，就不能再在子类中使用注解。
```

2021-04-07 04:24 UTC, Neo42 commented on docs/observable-state.md
> +1. `makeObservable`，`extendObservable` 不能再其它内置可观察类型上使用（`ObservableMap`，`ObservableSet`，`ObservableArray` 等）。
```suggestion
1. `makeObservable`，`extendObservable` 不能在其它内置可观察类型上使用（`ObservableMap`，`ObservableSet`，`ObservableArray` 等）。
```

2021-04-07 05:05 UTC, Neo42 commented on docs/observable-state.md
> +1. `makeObservable(Object.create(prototype))` 将属性从 `prototype` 拷贝到新创建的对象并且使得其是可观察的。此行为是错误的、不可预测的，因此将会在将来的版本中被 **废弃**。不要使用它。
```suggestion
1. `makeObservable(Object.create(prototype))` 将属性从 `prototype` 拷贝到新创建的对象并且使得其是可观察的。此行为是错误的、不可预测的，因此已经被**废弃**并有可能会在未来有所变动。不要使用它。
```

2021-04-07 05:11 UTC, Neo42 commented on docs/observable-state.md
> +上面的 API 都有一个可选的 `options` 参数，该参数是包含一下字段的对象：
```suggestion
上面的 API 都有一个可选的 `options` 参数，该参数是一个对象，支持以下选项：
```
建议把选项换到句尾，引出列举

2021-04-07 05:21 UTC, Neo42 commented on docs/observable-state.md
> +-   **`autoBind: true`** 默认使用 `action.bound`，而不使用 `action`。不影响显式注释的成员。
```suggestion
-   **`autoBind: true`** 默认使用 `action.bound`，而不使用 `action`。不影响被显式注释过的成员。
```

2021-04-07 05:21 UTC, Neo42 commented on docs/observable-state.md
> +-   **`deep: false`** 默认使用 `observable.ref`，而不使用 `observable`。不影响显式注释的成员。
```suggestion
-   **`deep: false`** 默认使用 `observable.ref`，而不使用 `observable`。不影响被显式注释过的成员。
```

2021-04-07 05:51 UTC, Neo42 commented on docs/observable-state.md
> +-   **`name: <string>`** 为对象提供一个调试名称，该名称将打印在错误消息和 reflection API 中。在生产中将被忽略。
```suggestion
-   **`name: <string>`** 为对象提供一个调试名称，该名称将被打印在错误消息和 reflection API 中。在生产环境中将被忽略。
```
这里的 reflection 和 production 可以再讨论讨论。
我在文档中暂时没发现有关 reflection 的解释，只是在 Mobx repo 的 discussion 里看到[作者提了一句](https://github.com/mobxjs/mobx/discussions/2856#discussioncomment-502483)，比较纠结这个怎么处理。还有“production”这个词，翻译成“生产”肯定是不对的，这个词一般翻译是“成品”，直观理解起来是说得通的，但问题是现在有普遍存在一种说法叫“生产环境”，这个说法虽然很别扭，但已经是业界习惯的译法了。可能还需要再讨论如何取舍的问题。

2021-04-07 05:58 UTC, Neo42 commented on docs/observable-state.md
> +-   **`proxy: false`** 强制 `observable(thing)` 使用非 [**proxy**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) 的实现。如果对象的结构不会随着时间变化，这是一个很好的选择，因为非代理对象更容易调试并且具有更快的
```suggestion
-   **`proxy: false`** 迫使 `observable(thing)` 使用非 [**proxy**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) 的实现。如果对象的结构不会随着时间变化，那么这就是一个很好的选择，因为非代理对象更容易调试并且速度更快。请参见 [避免代理](#avoid-proxies)。
```

2021-04-07 06:04 UTC, Neo42 commented on docs/observable-state.md
> +<details id="one-options-per-target"><summary>**注意：** options 是 *sticky* 并且只能被提供一次<a href="#one-options-per-target" class="tip-anchor"></a></summary>
```suggestion
<details id="one-options-per-target"><summary>**注意：** options 是*粘性的*并且只能被提供一次<a href="#one-options-per-target" class="tip-anchor"></a></summary>
```

2021-04-07 06:14 UTC, Neo42 commented on docs/observable-state.md
> +`options` 参数可以在 `target` 还不是可观察对象时提供。<br>
```suggestion
`options` 参数可以只被提供给还不是可观察对象的 `target`。<br>
```
或者
```suggestion
你可以只为还不是可观察对象的 `target` 提供 `option` 参数。<br>
```

2021-04-07 06:28 UTC, Neo42 commented on docs/observable-state.md
> +options 被保存在 target 上并且在之后的 `makeObservable`/`extendObservable` 调用中将会被保持。<br>
```suggestion
options 会被保存在 target 中并且不会被之后的 `makeObservable`/`extendObservable` 调用干扰。<br>
```
[respect](https://www.merriam-webster.com/dictionary/respect)：受干扰

2021-04-07 06:30 UTC, Neo42 commented on docs/observable-state.md
> +你不能在 [子类](subclassing.md) 中传递不同的 options。
```suggestion
你不能对 [子类](subclassing.md) 传入不同的 options。
```

2021-04-07 06:31 UTC, Neo42 commented on docs/observable-state.md
> +有时有必要将可观察的数据结构转换回原始的数据结构。
```suggestion
有时有必要将可观察的数据结构转换回原生的数据结构。
```
原生是比较习惯的说法

2021-04-07 06:40 UTC, Neo42 commented on docs/observable-state.md
> +例如，当将可观察对象传递到无法跟踪可观察对象的 React 组件时，或这想要获得将来不会改变的数据的克隆时。
```suggestion
例如，将可观察对象传入一个无法跟踪可观察对象的 React 组件时，或者想要获取一个不会再被更改的副本时。
```
传入
获取
further 再

2021-04-07 06:43 UTC, Neo42 commented on docs/observable-state.md
> +对于类，建议实现一个 `toJSON()` 方法，将会由 `JSON.stringify`调用。
```suggestion
对于类，建议实现一个 `toJSON()` 方法，因为这样会被 `JSON.stringify` 识别出来。
```

2021-04-07 06:47 UTC, Neo42 commented on docs/observable-state.md
> +要进行浅转换，一些常用的 JavaScript 语法糖会非常有用：
```suggestion
要进行浅转换，用常用的 JavaScript 操作就可以做到：
```
... work: ...就行，就可以
[mechanisms](https://www.merriam-webster.com/dictionary/mechanism): 机制；操作

2021-04-07 06:53 UTC, Neo42 commented on docs/observable-state.md
> +MobX 原则上对此没有限制，并且可能有许多使用普通对象的 MobX 用户。
```suggestion
MobX 原则上对此没有限制，而且可能有同样多的MobX 用户使用的是普通对象。
```
just as many：同样多

2021-04-07 07:08 UTC, Neo42 commented on docs/observable-state.md
> +但是，使用类的一个好处是更容易被索引以实现自动补全等功能，例如使用 TypeScript。
```suggestion
但是，使用类的一点好处是类中有更多很容易就能找到的 API，例如 TypeScript。
```
a slight benefit 一点好处
[discoverable](https://dictionary.cambridge.org/zhs/%E8%AF%8D%E5%85%B8/%E8%8B%B1%E8%AF%AD/discoverable): 容易发现或找到:

2021-04-07 07:12 UTC, Neo42 commented on docs/observable-state.md
> +另外，`instanceof` 非常强大，可以方便的用于类型推断，并且类实例不会被包装在 `Proxy` 对象中，从而提供更好的调试体验。
```suggestion
另外，`instanceof` 检查对于类型推断来说非常强大，并且类实例不会被包装在 `Proxy` 对象中，这一点给了它们更好的调试体验。
```

2021-04-07 07:14 UTC, Neo42 commented on docs/observable-state.md
> +最后，使用类可以从引擎优化中受益，因为它们是可预测的并且方法在原型上是共享的。
```suggestion
最后，使用类会从引擎优化中受益良多，因为它们的形态是可预测的并且方法在原型上是共享的。
```
a lot
shape

2021-04-07 07:18 UTC, Neo42 commented on docs/observable-state.md
> +因此，尽管稍微倾向于使用类，但如果有更适合您的，我们肯定会鼓励您偏离这种风格。
```suggestion
因此，尽管稍微倾向于使用类，但如果有更适合您的，我们肯定会鼓励您不采用这种风格。
```
个人认为偏离一般搭配路线，背离又有点太绝对，建议用不遵循或不采用

2021-04-07 07:19 UTC, Neo42 commented
@wangjq4214 校对完毕，望斟酌

2021-05-09 07:45 UTC, merged