docs: translate actions.md
mobxjs/zh.mobx.js.org pull request #11
Opened 2021-02-27 09:27 UTC by wangjq4214

2021-02-27 11:37 UTC, BlackHole1 requested changes

2021-02-27 11:37 UTC, BlackHole1 commented on docs/actions.md
> +## 关闭 flows {🚀}
取消

2021-02-27 14:31 UTC, wangjq4214 commented
@iChenLei 处理一下这个？

2021-04-07 08:06 UTC, Neo42 commented on docs/actions.md
> +所有的应用程序都有 actions。actions 是一些修改 state 的代码。原则上，actions 总是为了响应事件而发生的。例如，点击了一个按钮，一些输入被改变，一个 websocket 消息被送达，等等。
```suggestion
所有的应用程序都有 actions。action 就是任意一段修改 state 的代码。原则上，actions 总会为了对一个事件做出响应而发生。例如，点击了一个按钮，一些输入被改变，一个 websocket 消息被送达，等等。 
```

2021-04-07 08:21 UTC, Neo42 commented on docs/actions.md
> +尽管 [`makeAutoObservable`](observable-state.md#makeautoobservable) 可以自动完成许多工作，但是 MobX 还是要求你声明你的 actions。Actions 可以帮助你更好的组织你的代码并提供一些性能优势：
```suggestion
尽管 [`makeAutoObservable`](observable-state.md#makeautoobservable) 可以自动帮你声明一部分 actions，但是 MobX 还是要求你声明你的 actions。Actions 可以帮助你更好的组织你的代码并提供以下性能优势：
```
this job 指代 声明 actions
以下

2021-04-07 08:34 UTC, Neo42 commented on docs/actions.md
> +1. 他们在 [transactions](api.md#transaction) 内部运行。在最外层的 action 完成之前，不会更新任何的可观察对象，从而确保在 action 完成之前，action 中产生的中间值或不完整的值对应用程序是不可见的。
```suggestion
1. 它们在 [transactions](api.md#transaction) 内部运行。任何可观察对象在最外层的 action 完成之前都不会被更新，这一点保证了在 action 完成之前，action 执行期间生成的中间值或不完整的值对应用程序的其余部分都是不可见的。
```

2021-04-07 08:36 UTC, Neo42 commented on docs/actions.md
> +2. 默认情况下，不允许在 actions 之外改变 state。这有助于在代码中清楚的定位状态更新发生的位置。
```suggestion
2. 默认情况下，不允许在 actions 之外改变 state。这有助于在代码中清楚地对状态更新发生的位置进行定位。
```

2021-04-07 08:42 UTC, Neo42 commented on docs/actions.md
> +`action` 注解应仅用于_修改_ state 的函数。派生其他信息（执行查询或者过滤数据）的函数_不应该_被标记为 actions，以允许 MobX 跟踪其调用。 带有 `action` 注解的成员是不可枚举的。
```suggestion
`action` 注解应该仅用于会_修改_ state 的函数。派生其他信息（执行查询或者过滤数据）的函数_不应该_被标记为 actions，以便 MobX 可以对它们的调用进行跟踪。 带有 `action` 注解的成员是不可枚举的。
```
仅供参考

2021-04-07 08:43 UTC, Neo42 commented on docs/actions.md
> +// 这样调用增量是安全的, 因为它已经绑定.
```suggestion
// 这样调用 increment 是安全的, 因为它已经被绑定了。
```
在这里把 increment 翻译出来，不太合适吧。。

2021-04-07 09:29 UTC, Neo42 commented on docs/actions.md
> +为了尽可能地利用 MobX 的事务性，应该尽可能地对外暴露 actions。如果类方法将会修改 state，最好将其标记为 actions。事件处理函数是最常见的事务，最好将其标识为 actions。因为一个未被标记为 actions 的事件处理函数调用两个 actions 将会生成两个事务。
```suggestion
为了尽可能地利用 MobX 的事务性，actions 应该尽可能被传到外围。如果一个类方法会修改 state，可以将其标记为 action。把事件处理函数标记为 actions 就更好了，因为最外层的事务起着决定性作用。一个未被标记的、会接着调用两个 actions 的事件处理函数仍然将会生成两个事务。
```

2021-04-07 09:36 UTC, Neo42 commented on docs/actions.md
> +为了更容易地创建事件处理函数，`action` 不仅仅是一个注解，更是一个高阶函数。可以使用函数作为参数来调用它，在这种情况下它将会返回具有相同签名的使用 `action` 包装过的函数。
```suggestion
为了帮助创建基于 action 的事件处理函数，`action` 不仅仅是一个注解，更是一个高阶函数。可以使用函数作为参数来调用它，在这种情况下它将会返回具有相同签名的使用 `action` 包装过的函数。
```

2021-04-07 09:41 UTC, Neo42 commented on docs/actions.md
> +actions 的另一个特征是它们是 [不可追踪](api.md#untracked) 的。当从副作用或者计算值（非常罕见）中调用 action 时，该 action 读取的可观察对象将不会计入依赖项。
```suggestion
actions 的另一个特征是它们是 [不可追踪](api.md#untracked) 的。当从副作用或者计算值（非常罕见）中调用 action 时，该 action 读取的可观察对象将不会算作 derivation 的依赖项。
```

2021-04-07 09:50 UTC, Neo42 commented on docs/actions.md
> +`makeAutoObservable`，`extendObservable` 和 `observable` 使用一种特殊的 `action` 叫做  `autoAction`，
```suggestion
`makeAutoObservable`，`extendObservable` 和 `observable` 使用一种特殊的 `action`，叫做  `autoAction`，
```

2021-04-07 09:51 UTC, Neo42 commented on docs/actions.md
> +这样做将会在运行时确定函数是 derivation 还是 action。
```suggestion
这样做将会在运行时确定一个函数是 derivation 还是 action。
```

2021-04-07 10:02 UTC, Neo42 commented on docs/actions.md
> +`makeAutoObservable`，`extendObservable` 和 `observable` 使用一种特殊的 `action` 叫做  `autoAction`，
```suggestion
`makeAutoObservable`，`extendObservable` 和 `observable` 使用一种特殊的 `action`， 叫做  `autoAction`，
```

2021-04-07 10:03 UTC, Neo42 commented on docs/actions.md
> +这样做将会在运行时确定函数是 derivation 还是 action。
```suggestion
它将会在运行时确定函数是 derivation 还是 action。
```

2021-04-07 10:18 UTC, Neo42 commented on docs/actions.md
> +`action.bound` 注解可用于将方法自动绑定到正确的实例，因此 `this` 总是正确地绑定在函数内部。
```suggestion
`action.bound` 注解可用于自动将方法绑定到正确的实例，这样 `this` 会始终被正确绑定在函数内部。
```

2021-04-07 10:20 UTC, Neo42 commented on docs/actions.md
> +使用：
```suggestion
用法：
```

2021-04-07 12:06 UTC, Neo42 commented on docs/actions.md
> +使用这个工具函数可以创建一个立即调用的临时 action。在异步代码中非常有用。
```suggestion
使用这个工具函数来创建一个会被立即调用的临时 action。在异步进程中非常有用。
```

2021-04-07 12:09 UTC, Neo42 commented on docs/actions.md
> +只有定义在 **prototype** 上的函数可以被子类 **overriden**：
```suggestion
只有定义在 **prototype** 上的函数可以被子类**覆盖**：
```

2021-04-07 12:09 UTC, Neo42 commented on docs/actions.md
> +为了将单个的 _action_ **绑定** 到 `this`，可以使用 `action.bound` 代替箭头函数。<br>
```suggestion
想要将单个的 _action_ **绑定** 到 `this`，可以使用 `action.bound` 代替箭头函数。<br>
```

2021-04-07 12:15 UTC, Neo42 commented on docs/actions.md
> +而且因为可观察对象是可变的，因此在 action 过程中保持对它们的引用一般是安全的。
```suggestion
而且因为可观察对象是可变的，因此在 action 执行过程中保持对它们的引用一般是安全的。
```

2021-04-07 12:27 UTC, Neo42 commented on docs/actions.md
> +这一点可以利用上述的 API 以多种方式实现，如下所示。
```suggestion
我们可以通过利用上述的 API 以多种方式实现这一点，如下所示。
```

2021-04-07 12:38 UTC, Neo42 commented on docs/actions.md
> +例如，在处理 Promise 时，更新 state 的处理程序应该使用 `action` 进行包装或者其本身就是 actions，如下所示。
```suggestion
例如，在处理 Promise 时，更新 state 的处理程序应该被 `action` 包装起来，或者被标记为 actions，如下所示。
```

2021-04-07 13:17 UTC, Neo42 commented on docs/actions.md
> +Promise 的处理程序是内联的，但是会在原始的 action 执行完成之后运行，因此需要使用 `action` 进行包装：
```suggestion
Promise 的决议处理程序是我们以内联的方式处理的，但是会在一开始的 action 执行完成之后运行，因此需要使用 `action` 对它们进行包装：
```
promise 中的 [resolution / resolve](https://github.com/domenic/promises-unwrapping/issues/128#issuecomment-709838745)
一开始的

2021-04-07 13:20 UTC, Neo42 commented on docs/actions.md
> +然而，在异步进程中更新可观察对象的每个步骤（tick）都应该被标识为 `action`。
tick 这里需不需要加个注释：（事件循环的一次迭代）？

2021-04-07 13:21 UTC, Neo42 commented on docs/actions.md
> +`await` 之后的任何操作都不在同一个 tick 中，因此它们需要使用 action 包装。
```suggestion
`await` 之后的任何操作都不与其同在一个 tick 中，因此它们需要使用 action 包装。
```

2021-04-07 13:22 UTC, Neo42 commented on docs/actions.md
> +在这里，我们利用了 `runInAction`：
```suggestion
在这里，我们可以利用 `runInAction`：
```

2021-04-07 13:25 UTC, Neo42 commented on docs/actions.md
> +使用：
```suggestion
用法：
```

2021-04-07 14:56 UTC, Neo42 requested changes

2021-04-07 14:56 UTC, Neo42 commented on docs/actions.md
> +`flow` 将 [generator 函数](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator) 作为唯一输入。
```suggestion
`flow` 将一个 [generator 函数](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator) 作为唯一输入。
```

2021-04-07 14:56 UTC, Neo42 commented on docs/actions.md
> +所以 `flow` 是 `async` / `await` 的一个替代方法，它不需要 `action` 的包装。它可以按照下面的方式工作：
```suggestion
所以 `flow` 是 `async` / `await` 的一个替代方案，不需要再用 `action` 进行包装。它可以按照下面的方式使用：
```

2021-04-07 14:56 UTC, Neo42 commented on docs/actions.md
> +上面的 [`flow` + generator 函数](#asynchronous-actions) 的示例展示了实际情况中的用法。
```suggestion
以上 [`flow` + generator 函数](#asynchronous-actions) 的示例展示了实际情况中的用法。
```

2021-04-07 14:56 UTC, Neo42 commented on docs/actions.md
> +需要注意的是，当使用 TypeScript 时才需要使用 `flowResult` 函数。
```suggestion
注意，使用 TypeScript 时才会需要 `flowResult` 函数。
```

2021-04-07 14:56 UTC, Neo42 commented on docs/actions.md
> +由于使用 `flow` 包装方法，他将把返回的 generator 包裹在 Promise 中。
```suggestion
它会因为使用 `flow` 装饰了一个方法而把返回的 generator 包裹在 Promise 中。
```

2021-04-07 14:56 UTC, Neo42 commented on docs/actions.md
> +然而，TypeScript 并不知道这种转换，因此使用 `flowResult` 确保 TypeScript 可以知道这种类型的改变。
```suggestion
然而，TypeScript 并不会意识到这种转换，因此 `flowResult` 确保 TypeScript 意识到这种类型的改变。
```

2021-04-07 14:56 UTC, Neo42 commented on docs/actions.md
> +`makeAutoObservable` 将自动推断 generators 为 `flow`。带有 `flow` 注解的成员是不可枚举的。
```suggestion
`makeAutoObservable` 和它的小伙伴们会把 generators 自动推断成 `flow`。带有 `flow` 注解的成员是不可枚举的。
```

2021-04-07 14:56 UTC, Neo42 commented on docs/actions.md
> +<details id="flow-wrap"><summary>{🚀} **注意：** 将 flow 作为对象字段<a href="#flow-wrap" class="tip-anchor"></a></summary>
```suggestion
<details id="flow-wrap"><summary>{🚀} **注意：** 将 flow 用于对象字段<a href="#flow-wrap" class="tip-anchor"></a></summary>
```

2021-04-07 15:00 UTC, Neo42 commented on docs/actions.md
> +像 `action` 一样，`flow` 也可以直接作为包装函数使用。上面的例子可以改写成下面的样子：
```suggestion
像 `action` 一样，`flow` 也可以直接用来包装函数。上面的例子本来还可以改写成下面的样子：
```

2021-04-07 15:04 UTC, Neo42 commented on docs/actions.md
> +这样做的好处是我们不再需要 `flowResult` 了，但是需要传入 `this` 来确保正确的类型推断。
```suggestion
这样做的好处是我们不再需要 `flowResult` 了，坏处是需要指定 `this` 的类型，以便确保它的类型会被正确推断出来。
```

2021-04-07 15:09 UTC, Neo42 commented on docs/actions.md
> +`flow` 的返回值是一个 Promise，在 generator 函数运行完成时它将会被 resolve。
```suggestion
`flow` 的返回值是一个 Promise，这个 promise 会用最后 generator 函数的返回值进行决议（resolve）。
```

2021-04-07 15:11 UTC, Neo42 commented on docs/actions.md
> +返回的 Promise 中有一个额外的 `cancel()` 方法，该方法可以中断正在运行的 generator 并取消它。
```suggestion
返回的 Promise 中还有一个 `cancel()` 方法，该方法可以打断正在运行的 generator 并取消它。
```

2021-04-07 15:12 UTC, Neo42 commented on docs/actions.md
> +`try` / `finally` 字句仍将运行。
```suggestion
所有 `try` / `finally` 语句仍然会被运行。
```

2021-04-07 15:13 UTC, Neo42 commented on docs/actions.md
> +## 关闭强制使用 action {🚀}
```suggestion
## 禁用强制性 action {🚀}
```

2021-04-07 15:14 UTC, Neo42 commented on docs/actions.md
> +默认情况下，MobX 6 和更高版本要求您使用 action 来更改 state。
```suggestion
默认情况下，MobX 6 和更高版本会要求您使用 action 来更改 state。
```

2021-04-07 15:15 UTC, Neo42 commented on docs/actions.md
> +然而，你可以配置 MobX 来关闭这个行为。查看 [`enforceActions`](configuration.md#enforceactions)。
```suggestion
然而，你可以配置 MobX 来禁用这个行为。查看 [`enforceActions`](configuration.md#enforceactions)。
```

2021-04-07 15:18 UTC, Neo42 commented on docs/actions.md
> +例如，这在单元测试中非常有用，因为警告并不总是有价值的。
```suggestion
例如，这在单元测试场景中非常有用，因为警告并不总是很有价值。
```
setup 除了指安装还可以指场景

2021-04-07 15:19 UTC, Neo42 commented
@wangjq4214 校对完毕，望斟酌。

2021-04-08 04:23 UTC, Neo42 commented on docs/actions.md
>  class Parent {
on prototype：原型方法
on instance：实例方法

2021-05-29 14:20 UTC, iChenLei commented
Thank u @wangjq4214, PR merged now.

2021-05-29 14:20 UTC, merged