docs: computeds.md
mobxjs/zh.mobx.js.org pull request #36
Opened 2021-02-27 14:21 UTC by wangjq4214

2021-02-28 05:06 UTC, wangjq4214 commented
@iChenLei 已完成

2021-03-06 03:06 UTC, iChenLei commented
cc @xdlrt @BlackHole1 `校对`

2021-03-06 03:16 UTC, BlackHole1 requested changes

2021-03-06 03:16 UTC, BlackHole1 commented on docs/computeds.md
> +// 如果你在 reaction 之外访问 `line.total`, 每次都会重新计算.
如果你在 reaction 之外访问 `line.total`，那么每次都会重新计算。

2021-04-08 02:55 UTC, Neo42 commented on docs/computeds.md
> +计算值可以从其他可观察对象中派生信息。
```suggestion
计算值可以用来从其他可观察对象中派生信息。
```

2021-04-08 13:26 UTC, Neo42 commented on docs/computeds.md
> +这样会避免在没有观察者调用时将其挂起（可以查看上面的解释）。与 [reactions](reactions.md#always-dispose-of-reactions) 的讨论类似，这可能会招致内存泄漏。
```suggestion
这个选项会避免计算值在未被观察时被暂时停用（可以查看上面的解释）。这可能会导致内存泄漏，这种内存泄漏与我们在 [reactions](reactions.md#always-dispose-of-reactions) 中讨论到的类似。
```
simillar to...修饰 memory leaks

2021-04-08 13:28 UTC, Neo42 commented
@wangjq4214 校对完毕，望斟酌。

2021-06-06 12:34 UTC, merged