docs: react-optimizations.md
mobxjs/zh.mobx.js.org pull request #44
Opened 2021-03-01 05:29 UTC by berber1016

1.start

2021-03-08 02:02 UTC, berber1016 commented
@iChenLei 翻译完毕～～～ 翻译阶段完结撒花🎉 麻烦各位大佬校对了

2021-03-08 05:04 UTC, iChenLei commented
cc @ObservedObserver @WanderWang  @BlackHole1

2021-03-08 06:03 UTC, BlackHole1 requested changes

2021-03-08 06:03 UTC, BlackHole1 commented on docs/react-optimizations.md
> +MobX非常快, [甚至要比Redux还要快](https://twitter.com/mweststrate/status/718444275239882753), 但本章节提供一些小贴士，以便充分利用 React 和 MobX。 请注意，大多数小贴士都适用于普通的 React，而非 MobX 专用的。
通常比 Redux 更快。

普通的 React -> 一般的 React

专用 -> 特有

2021-03-08 06:03 UTC, BlackHole1 commented on docs/react-optimizations.md
> +在上面的示例中，当 user.name 改变时，React 会不必要地协调所有的 TodoView 组件。尽管TodoView 组件不会重新渲染，但是协调的过程本身是非常昂贵的。
《尽管TodoView》 缺失空格

缺失 **\`**

2021-03-10 03:25 UTC, berber1016 commented on docs/react-optimizations.md
> +MobX非常快, [甚至要比Redux还要快](https://twitter.com/mweststrate/status/718444275239882753), 但本章节提供一些小贴士，以便充分利用 React 和 MobX。 请注意，大多数小贴士都适用于普通的 React，而非 MobX 专用的。
收到 我最近抽时间修改一下

2021-03-10 03:25 UTC, berber1016 commented on docs/react-optimizations.md
> +在上面的示例中，当 user.name 改变时，React 会不必要地协调所有的 TodoView 组件。尽管TodoView 组件不会重新渲染，但是协调的过程本身是非常昂贵的。
收到 我最近抽时间修改一下

2021-03-10 04:08 UTC, iChenLei commented on docs/react-optimizations.md
> +MobX非常快, [甚至要比Redux还要快](https://twitter.com/mweststrate/status/718444275239882753), 但本章节提供一些小贴士，以便充分利用 React 和 MobX。 请注意，大多数小贴士都适用于普通的 React，而非 MobX 专用的。
@berber1016 不着急哈这里没有deadline.，大家都是抽时间来做翻译工作，很感谢各位译者的付出。 ❤️

2021-04-09 06:35 UTC, berber1016 commented
@BlackHole1  我这边改完了，麻烦你再核对一下，谢谢🙏

2021-04-09 06:42 UTC, iChenLei commented
@berber1016 其实不需要手动rebase然后force-push，合并PR的时候会squash成一个commit

2021-05-09 07:25 UTC, merged