docs: api.md
mobxjs/zh.mobx.js.org pull request #50
Opened 2021-03-04 07:23 UTC by Neo42

2021-03-12 16:48 UTC, Neo42 commented
翻译完毕 @iChenLei

2021-03-13 01:37 UTC, iChenLei commented
感谢Neo42同学的翻译工作
cc @BlackHole1 @wangjq4214 @WanderWang
> 这篇是所有api的介绍 大家仔细看看 一般文档访问率最高的应该就是这篇

2021-04-02 11:05 UTC, wuxyman requested changes
以上是一些建议，望斟酌。

2021-04-02 12:54 UTC, Neo42 commented
> 以上是一些建议，望斟酌。

感谢！我会尽快处理！

2021-04-04 05:58 UTC, Neo42 commented on docs/api.md
> +_把事物转化成 observable。_
这个词比较难处理。

如果从词典中找的话，英文的解释一般都是 “that can be noticed or seen”，跟你的译法是一致的。还有一种物理学上的 “observable” 可观察量（不过好像又跟在这里的含义不一样）。

观察者模式里的 observable 跟这里比较接近。wiki 上解释[观察者模式](https://en.wikipedia.org/wiki/Observer_pattern)时并没有解释什么是 observable，只在代码示例里写了几种语言中 observable 的用法。我翻了几本设计模式的教材，它们在讲观察者模式的时候都不会把 observable 按词典解释翻译，一般都是保留原文（Head First 设计模式、四人帮的设计模式教材），尤其是在讲到代码的时候（比如说 Java 的内置 observable）。可以类比 generator、promise 和 async/await 的翻译理解，如果翻译出来的话，写代码的时候理解起来就可能不太直接。

还可以参考 [rxjs 的官方中文文档](https://cn.rx.js.org/manual/overview.html#observable-)，他们在开头给了一个“（可观察对象）”的注解，其他地方基本上都保留了原文。

当然也不能说“可观察的”翻译得不对。这可能最后还是约定习惯的问题。可以等咱们的进度到可以考虑规范了再商量商量。

2021-04-04 09:05 UTC, Neo42 commented on docs/api.md
> +克隆一个对象并把它转化成 observable。`source` 可以是一个普通的对象、数组、Map 或 Set。默认情况下，`observable` 会递归执行。如果遇到的值中有一个是对象或数组，那么该值也会被传入 `observable`。
这里用 `source` 也是因为可以对应上面的用法注解，方便理解。如果翻译成“来源”的话，跟“克隆”搭配来看有点不符合中文习惯：“克隆的来源”。

顺便一句，说实话，“Source ...” 这句话的英文原文的语法出错了，少了一个冠词 the。不过如果这句话出现在口语中就不用纠结这个了。

可以具体说一下建议不翻译 plain object 的原因吗？

2021-04-04 11:23 UTC, Neo42 commented on docs/api.md
> +在一个 observable API 发生改变之前将该改变拦截。返回一个阻止拦截的处置函数。
如果说 intercepts 是名词，那它就是个复数名词，所以谓语 change 就不应该加 s，跟原文是矛盾的

2021-04-04 11:24 UTC, Neo42 commented on docs/api.md
> +渲染被传入的 render 函数，并在 render 函数所使用的 observable 之一发生改变时将函数重新渲染。
👍

2021-04-04 11:27 UTC, Neo42 commented on docs/api.md
> +忽略在所赋值的结构中与当前值相等的值，除此之外和 `observable` 注解类似。
👍 这句是我走神写错了

2021-04-04 11:48 UTC, Neo42 commented on docs/api.md
> +使用 `makeObservable` 创建一个新的 observable，并在组件的整个生命周期内将其保留在组件中。
keep around 一般翻译成“带着，留着”
比如说：带本书 => keep a book around；把狗狗带在身边 => keep the puppy around
所以我才考虑用“保留”
“使其作用于”确实符合实际效果，不过没有把 in the component 体现出来

2021-04-05 07:38 UTC, Neo42 commented on docs/api.md
> +可以在某个值开始被监控时使用的钩子函数。
“become observed” 跟 “become observable” 是不一样的。这个钩子函数是用在已有的 observable 上的。可以参考 [Creating Lazy Observables](https://mobx.js.org/lazy-observables.html#creating-lazy-observables-)

2021-04-05 07:40 UTC, Neo42 commented on docs/api.md
> -Computed values and other non-enumerable properties won't be part of the result.
👍

2021-04-05 08:51 UTC, Neo42 commented on docs/api.md
> +根据被传入的 `initialValues` 创建一个新的 observable 数组。如果要把 observable 数组转化回普通的数组，就请使用 `.slice()` 方法，或者参阅 [toJS](#tojs) 进行递归转化。除了语言中内置的所有数组方法之外，observable 数组中还有以下好东西可以使用：
明白。我之前想多了。

2021-04-05 11:40 UTC, Neo42 commented on docs/api.md
> +返回一个树形结构，其中包含被传入的 reaction 或计算值当前依赖的所有 observable。
👍

2021-04-05 12:58 UTC, Neo42 commented
@wuxyman 感谢校对！一部分已经按同学的建议改了，其余的可能还有待商榷，麻烦再看一下，谢谢~

2021-04-06 02:20 UTC, wuxyman commented on docs/api.md
> +_把事物转化成 observable。_
嗯，确实，mobx里这个observable感觉是框架用这个单词来描述的一个概念。其实作用比较接近监听、被监听。但是监听明显又不是这个单词，这个还真是需要所有地方统一这个概念，如果文档对这一概念不统一，怕是看各个文档会出现理解偏差

2021-04-06 02:37 UTC, wuxyman commented on docs/api.md
> +克隆一个对象并把它转化成 observable。`source` 可以是一个普通的对象、数组、Map 或 Set。默认情况下，`observable` 会递归执行。如果遇到的值中有一个是对象或数组，那么该值也会被传入 `observable`。
source 我这里是想翻的更容易明白点，并没有一定要依照单词本身的意思。只是从前一句，感觉比较符合汉语理解，把这一句作为前一句的补充。
plain object 好像有的翻译是纯对象，纯对象是object.create(null)创建的，let obj = {}创建的是普通对象。其实折2个是不一样的。而且后面Map、Set也没有翻译，所以就想着都不翻译。

2021-04-06 03:00 UTC, wuxyman commented on docs/api.md
> +使用 `makeObservable` 创建一个新的 observable，并在组件的整个生命周期内将其保留在组件中。
嗯，我的意思就是把这个作用说明白就行，有时候对概念理解如果没有问题的话就尽量简洁些。有些英文的就不翻那么逐字逐句。

2021-04-06 03:05 UTC, wuxyman commented on docs/api.md
> +在一个 observable API 发生改变之前将该改变拦截。返回一个阻止拦截的处置函数。
我感觉英文原文这里changes应该是多了个s，后面的they are应该指的就是拦截器。所以主句是  拦截器会发生改变。
before they are applied to an observable API 作为状语。按汉语习惯，把状态语句前置方便理解。

2021-04-06 03:08 UTC, wuxyman commented on docs/api.md
> +可以在某个值开始被监控时使用的钩子函数。
嗯，这里我的理解有问题。

2021-04-06 03:10 UTC, wuxyman commented
@Neo42    已对有待商榷部分作出回答，望斟酌。

2021-04-06 03:13 UTC, iChenLei commented
@wuxyman  https://github.com/mobxjs/zh.mobx.js.org/issues/25 已释放，欢迎认领翻译

2021-04-06 04:16 UTC, Neo42 commented on docs/api.md
> +在一个 observable API 发生改变之前将该改变拦截。返回一个阻止拦截的处置函数。
那如果原文的意思是 “(This method) Intercepts changes before they are applied to an observable API.” 呢？
这样是说得通的，也符合 [Intercept & Observe](https://mobx.js.org/intercept-and-observe.html) 的介绍。
> `intercept` can be used to detect and modify mutations before they are applied to the observable (validating, normalizing or cancelling).

2021-04-06 07:13 UTC, Neo42 commented on docs/api.md
> +克隆一个对象并把它转化成 observable。`source` 可以是一个普通的对象、数组、Map 或 Set。默认情况下，`observable` 会递归执行。如果遇到的值中有一个是对象或数组，那么该值也会被传入 `observable`。
那把 `source` 改成源对象可不可以？中文读起来比较顺口

plain object 这里可以用 Mobx 内置的 [`isPlainObject`]() 方法测试一下：

```js
const plainObjectString = Object.toString()

function isObject(value: any): value is Object {
    return value !== null && typeof value === "object"
}

function isPlainObject(value) {
    if (!isObject(value)) return false
    const proto = Object.getPrototypeOf(value)
    if (proto == null) return true
    return proto.constructor?.toString() === plainObjectString
}

isPlainObject({});					// true
isPlainObject(Object.create(null)) 	// true
isPlainObject([]);					// false
isPlainObject(new Map());			// false
isPlainObject(new Set());			// false
```
`object.create(null)` 是被判定为 plain object 的。

应该是每个工具对于 plain object 的界定不一样，像 [Redux](https://github.com/reduxjs/redux/blob/master/src/utils/isPlainObject.ts) 里只有 `{}` 才算 plain object：

```js
function isPlainObject(obj) {
  if (typeof obj !== 'object' || obj === null) return false

  let proto = obj
  while (Object.getPrototypeOf(proto) !== null) {
    proto = Object.getPrototypeOf(proto)
  }

  return Object.getPrototypeOf(obj) === proto
}

isPlainObject({});					// true
isPlainObject(Object.create(null)) 	// false
isPlainObject([]);					// false
isPlainObject(new Map());			// false
isPlainObject(new Set());			// false
```

2021-04-06 09:08 UTC, Neo42 commented on docs/api.md
> +使用 `makeObservable` 创建一个新的 observable，并在组件的整个生命周期内将其保留在组件中。
我理解你的意思，理解概念是好的，不过如果考虑一下这里的场景的话，其实按原文翻译还是有必要的。毕竟这只是个 api 的清单，这个钩子函数的描述只有一句话，所以描述跟 api 名字的联系：“local”（局部） -> “保留在组件中” 可能还是保留下来比较好。在这里尽量按原文翻译的话，出错概率会小很多。

2021-04-06 09:11 UTC, Neo42 commented
@wuxyman 已回复，望斟酌。

2021-05-09 07:17 UTC, merged