lazy-observables.md
mobxjs/zh.mobx.js.org pull request #69
Opened 2021-04-07 02:51 UTC by wuxyman

2021-04-07 04:19 UTC, wuxyman commented
@iChenLei  翻译完了

2021-04-07 04:33 UTC, iChenLei commented
辛苦同学翻译 /cc @Neo42 @BlackHole1

2021-04-08 04:03 UTC, BlackHole1 requested changes

2021-04-08 04:03 UTC, BlackHole1 commented on docs/lazy-observables.md
> +        // 数据获取逻辑...
```diff
- 数据获取逻辑...
+ 获取数据的逻辑...
```

2021-06-16 11:21 UTC, merged