docs: Migrating from MobX 4/5
mobxjs/zh.mobx.js.org pull request #73
Opened 2021-04-10 04:05 UTC by wuxyman

2021-04-11 17:19 UTC, wuxyman commented
@iChenLei  已翻译完，需要更新标签

2021-04-12 00:19 UTC, iChenLei commented
/cc @Neo42 @BlackHole1

2021-04-16 10:09 UTC, ObservedObserver requested changes

2021-04-16 10:09 UTC, ObservedObserver commented on docs/migrating-from-4-or-5.md
> +2. `makeAutoObservable`将使用新的装饰器`autoAction`标记方法，只有当方法不在派生上下文中时，它才会应用`action`。这使得从计算属性中调用自动装饰的方法也很安全。
`derivation context`最好不要直接写成”派生上下文“。这里`derivation` 属于mobx中的概念，建议保留英文原词，不做直译。

参考[相关讨论](https://github.com/mobxjs/zh.mobx.js.org/issues/35#issuecomment-792436224)

2021-04-16 10:09 UTC, ObservedObserver commented on docs/migrating-from-4-or-5.md
> +[`mobx-undecorate`](https://www.npmjs.com/package/mobx-undecorate) 包提供了一个codemod可以自动更新你的代码，使其更加符合MobX 6。此包无需安装;你只需要下载并使用[`npx`](https://www.npmjs.com/package/npx) 工具，如果你还没有npx工具你必须安装。
1. ”你只需要下载并使用[`npx`](https://www.npmjs.com/package/npx) 工具，如果你还没有npx工具你必须安装。“。这句话在中文里读起来有点怪怪的，主语太多了，有的”你“可以省略。
2. 这里的分号用的是半角

2021-04-16 15:25 UTC, wuxyman commented on docs/migrating-from-4-or-5.md
> +2. `makeAutoObservable`将使用新的装饰器`autoAction`标记方法，只有当方法不在派生上下文中时，它才会应用`action`。这使得从计算属性中调用自动装饰的方法也很安全。
嗯，已处理，感谢讨论

2021-04-16 15:27 UTC, wuxyman commented on docs/migrating-from-4-or-5.md
> +[`mobx-undecorate`](https://www.npmjs.com/package/mobx-undecorate) 包提供了一个codemod可以自动更新你的代码，使其更加符合MobX 6。此包无需安装;你只需要下载并使用[`npx`](https://www.npmjs.com/package/npx) 工具，如果你还没有npx工具你必须安装。
已更改，感谢反馈

2021-06-06 03:56 UTC, merged